# _config.yml

title: "Mohsin Ayoub's Portfolio"
logo: "/PIC Portfolio.png"
## Software Engineer | Frontend Engineer

---

### 📫 Connect with Me

[![LinkedIn](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/vishalraj1/)
[![Gmail](https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white)](mailto:rajputvishal33876@gmail.com)

author: Mohsin Ayoub
email: mohsinabbasi009@gmail.com
theme: jekyll-theme-minimal
baseurl: "" # Leave blank unless the site is hosted in a subdirectory
url: "https://your-github-username.github.io" # Replace with your GitHub Pages URL

# Social links
social_links:
  - name: LinkedIn
    url: "https://linkedin.com/in/mohsin-ayoub"
  - name: GitHub
    url: "https://github.com/Mohsin-Ayoub/mohsin-ayoub.github.io"
  - name: WhatsApp
    url: "https://wa.me/923421544632"

# Navigation links
nav_links:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Projects"
    url: "/projects"
  - title: "Contact"
    url: "/contact"

# Markdown options
markdown: kramdown
kramdown:
  input: GFM
